// Records docs/demo.gif — the animation shown in the README — by scrolling the
// published demo in a real browser and encoding the frames with ffmpeg.
//
// The clip is built to loop seamlessly: it starts and ends at the top of the
// page with nothing revealed, its length is a whole number of bob cycles, and
// the bob's phase is set explicitly per frame rather than left to wall-clock,
// so capture jitter cannot drift the caret out of sync with the loop point.
//
// Requires ffmpeg on PATH. Run `npm run build:docs` first, then `npm run demo:gif`.
// Committed output, regenerated by hand when the demo changes; CI does not run this.
import {createServer} from 'node:http';
import {mkdtemp, readFile, rm} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {tmpdir} from 'node:os';
import {dirname, extname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = join(root, 'docs/demo.gif');

const FPS = 12;
const WIDTH = 720;
/** Must match the .bob animation-duration in demo/index.html. */
const BOB_SECONDS = 1.5;

const run = (command, args) =>
  new Promise((resolve, reject) => {
    const child = spawn(command, args, {stdio: ['ignore', 'ignore', 'inherit']});
    child.on('error', reject);
    child.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`${command} exited ${code}`))));
  });

const mime = {'.html': 'text/html', '.js': 'text/javascript', '.gif': 'image/gif'};
const server = createServer(async (request, response) => {
  try {
    const path = join(root, 'docs', new URL(request.url, 'http://localhost').pathname);
    const body = await readFile(path);
    response.writeHead(200, {'content-type': mime[extname(path)] ?? 'text/plain'});
    response.end(body);
  } catch {
    response.writeHead(404).end('not found');
  }
});
await new Promise((resolve) => server.listen(0, resolve));

const frames = await mkdtemp(join(tmpdir(), 'aos-frames-'));
const browser = await chromium.launch();

try {
  const page = await browser.newPage({viewport: {width: 900, height: 600}, deviceScaleFactor: 1});
  await page.goto(`http://localhost:${server.address().port}/index.html`);
  await page.waitForSelector('.appear-on-scroll', {state: 'attached'});
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(700);

  let frame = 0;
  const shoot = async () => {
    // Pin the caret to an exact point in its cycle for this frame, so the last
    // frame lands on the same phase as the first however long capture took.
    // Set the animation's currentTime rather than a negative animation-delay:
    // a delay is added to however long the animation has already been running,
    // so it shifts the phase without pinning it.
    const elapsed = ((frame / FPS) % BOB_SECONDS) * 1000;
    await page.evaluate((currentTime) => {
      const [bob] = document.querySelector('.bob').getAnimations();
      bob.pause();
      bob.currentTime = currentTime;
    }, elapsed);
    await page.screenshot({path: join(frames, `f${String(frame++).padStart(4, '0')}.png`)});
  };

  const sectionTop = (selector) =>
    page.evaluate((s) => document.querySelector(s).getBoundingClientRect().top + window.scrollY - 80, selector);

  /** Ease the scroll so it reads as a person moving — that is what makes the direction-aware slide legible. */
  const glideTo = async (target, seconds) => {
    const from = await page.evaluate(() => window.scrollY);
    const steps = Math.round(seconds * FPS);
    for (let step = 1; step <= steps; step++) {
      const t = step / steps;
      const eased = t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2;
      await page.evaluate((y) => window.scrollTo(0, y), from + (target - from) * eased);
      await shoot();
    }
  };
  const hold = async (seconds) => {
    for (let i = 0; i < Math.round(seconds * FPS); i++) {
      await page.waitForTimeout(1000 / FPS);
      await shoot();
    }
  };

  const slide = await sectionTop('#slide');
  const stagger = await sectionTop('#stagger');

  // 6.0s exactly: four bob cycles, and back to where it started.
  await hold(0.5);
  await glideTo(slide, 1.0);
  await hold(0.75);
  await glideTo(stagger, 1.0);
  await hold(1.0); // the whole cascade: nine cells at 90ms, then a 500ms reveal
  await glideTo(0, 1.25); // back up, so the same cards settle from above
  await hold(0.5);

  const seconds = frame / FPS;
  const cycles = seconds / BOB_SECONDS;
  if (!Number.isInteger(cycles)) {
    throw new Error(`${seconds}s is ${cycles} bob cycles; the caret will jump at the loop point`);
  }

  // The loop only reads as a loop if the last frame steps back onto the first.
  // Compare them before spending time encoding.
  const [firstFrame, lastFrame] = await Promise.all([
    readFile(join(frames, 'f0000.png')),
    readFile(join(frames, `f${String(frame - 1).padStart(4, '0')}.png`)),
  ]);
  if (!firstFrame.equals(lastFrame)) {
    throw new Error(
      'first and last frame differ, so the loop will visibly jump. Something on the ' +
        'page is still settling at the end of the clip, or an animation is not pinned.',
    );
  }

  // Two passes: one palette for the whole clip, so the dark surfaces do not band.
  const palette = join(frames, 'palette.png');
  const scale = `scale=${WIDTH}:-1:flags=lanczos`;
  const input = ['-framerate', String(FPS), '-i', join(frames, 'f%04d.png')];
  await run('ffmpeg', [
    '-y',
    '-loglevel',
    'error',
    ...input,
    '-vf',
    `${scale},palettegen=max_colors=96:stats_mode=diff`,
    palette,
  ]);
  await run('ffmpeg', [
    '-y',
    '-loglevel',
    'error',
    ...input,
    '-i',
    palette,
    '-lavfi',
    `${scale}[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle`,
    '-loop',
    '0',
    OUTPUT,
  ]);

  console.log(`docs/demo.gif: ${frame} frames, ${seconds}s at ${FPS}fps, ${cycles} bob cycles, loop seam exact`);
  if (process.env.KEEP_FRAMES) console.log(`frames kept at ${frames}`);
} finally {
  await browser.close();
  server.close();
  if (!process.env.KEEP_FRAMES) await rm(frames, {recursive: true, force: true});
}
