// Records docs/demo.gif — the animation shown in the README — by scrolling the
// published demo in a real browser and encoding the frames with ffmpeg.
//
// Requires ffmpeg on PATH. Run `npm run build:docs` first, then `node scripts/record-demo.mjs`.
// Committed output, regenerated by hand when the demo changes; CI does not run this.
import {createServer} from 'node:http';
import {mkdtemp, readFile, rm} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {tmpdir} from 'node:os';
import {dirname, extname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = join(root, 'docs/demo.gif');

/** Capture rate. The GIF is encoded at 12 to keep it under a couple of megabytes. */
const CAPTURE_FPS = 15;
const GIF_FPS = 12;
const GIF_WIDTH = 720;

const run = (command, args) =>
  new Promise((resolve, reject) => {
    const child = spawn(command, args, {stdio: ['ignore', 'ignore', 'inherit']});
    child.on('error', reject);
    child.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`${command} exited ${code}`))));
  });

const mime = {'.html': 'text/html', '.js': 'text/javascript'};
const server = createServer(async (request, response) => {
  try {
    const path = join(root, 'docs', new URL(request.url, 'http://localhost').pathname);
    response.writeHead(200, {'content-type': mime[extname(path)] ?? 'text/plain'}).end(await readFile(path));
  } catch {
    response.writeHead(404).end('not found');
  }
});
await new Promise((resolve) => server.listen(0, resolve));

const frames = await mkdtemp(join(tmpdir(), 'aos-frames-'));
const browser = await chromium.launch();

try {
  const page = await browser.newPage({viewport: {width: 900, height: 600}, deviceScaleFactor: 1});
  await page.goto(`http://localhost:${server.address().port}/index.html`);
  await page.waitForSelector('.appear-on-scroll', {state: 'attached'});
  await page.waitForTimeout(700);

  let frame = 0;
  const shoot = () => page.screenshot({path: join(frames, `f${String(frame++).padStart(4, '0')}.png`)});
  const sectionTop = (selector) =>
    page.evaluate((s) => document.querySelector(s).getBoundingClientRect().top + window.scrollY - 80, selector);

  /** Ease the scroll so it reads as a person moving — that is what makes the direction-aware slide legible. */
  const glideTo = async (target, seconds) => {
    const from = await page.evaluate(() => window.scrollY);
    const steps = Math.round(seconds * CAPTURE_FPS);
    for (let step = 1; step <= steps; step++) {
      const t = step / steps;
      const eased = t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2;
      await page.evaluate((y) => window.scrollTo(0, y), from + (target - from) * eased);
      await shoot();
    }
  };
  const hold = async (seconds) => {
    for (let i = 0; i < Math.round(seconds * CAPTURE_FPS); i++) {
      await page.waitForTimeout(1000 / CAPTURE_FPS);
      await shoot();
    }
  };

  await hold(0.5);
  await glideTo(await sectionTop('#slide'), 1.3); // scrolling down: cards rise from below
  await hold(1.2);
  await glideTo(await sectionTop('#stagger'), 1.5);
  await hold(1.9); // long enough for the whole cascade: nine cells at 90ms, then a 500ms reveal
  await glideTo(await sectionTop('#slide'), 1.5); // scrolling back up: the same cards settle from above
  await hold(1.5);

  // Two passes: one palette for the whole clip, so the dark surfaces do not band.
  const palette = join(frames, 'palette.png');
  const scale = `fps=${GIF_FPS},scale=${GIF_WIDTH}:-1:flags=lanczos`;
  const input = ['-framerate', String(CAPTURE_FPS), '-i', join(frames, 'f%04d.png')];
  await run('ffmpeg', [
    '-y',
    '-loglevel',
    'error',
    ...input,
    '-vf',
    `${scale},palettegen=max_colors=96:stats_mode=diff`,
    palette,
  ]);
  await run('ffmpeg', [
    '-y',
    '-loglevel',
    'error',
    ...input,
    '-i',
    palette,
    '-lavfi',
    `${scale}[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle`,
    OUTPUT,
  ]);

  console.log(`docs/demo.gif written from ${frame} frames`);
} finally {
  await browser.close();
  server.close();
  await rm(frames, {recursive: true, force: true});
}
